### ISSUE TITLE
Flatten not available

### ISSUE THREAD

**Issue by treksn** [VigneshSrinivasan10/interprettensor#4]
Hello,

I would like to use the Flatten operation. I saw that you used it in some files, but the file is not in the modules folder. Is this on purpose?
I tried to use the Flatten from the lrp-toolbox, but it isn't working. 
Can you help me with this?
Thank you!

**Comment by VigneshSrinivasan10** [comment]
Hi @treksn, 

Currently we support only linear and conv2d operations which require either a 2D or a 4D tensor respectively. Hence, it was natural to perform the reshape as required within the scope of these modules - like in
https://github.com/VigneshSrinivasan10/interprettensor/blob/b9002d80a1e794878514a388b7b897f9f749cefb/interprettensor/modules/convolution.py#L64

We have further plans to expand this library to include more modules like conv3d and also LSTM. When that happens in the future, for clarity, we will add the 'flatten' as a seperate module (though, it will take some time).  

Best,

**Comment by treksn** [comment]
Okay, thank you for the fast answer.
