### ISSUE TITLE
What is difference lrp algorithm between here and heatmapping.org tutorial?

### ISSUE THREAD

**Issue by wjNam** [VigneshSrinivasan10/interprettensor#8]
Hi, I'm studying about interpretting the deep learning and followed your code to implement the lrp.

But there is a memory problem of your code that extract_patches() function consumes a lot of memory and time in case large network such as 3D convolution.

So i followed the code in heatmapping.org tutorial to implement the code and it works in my network.

I thought that it works, but i found that the result is different between tutorial and your code when i tested in small network.
```

class FirstConvolution(modules.Convolution):
    def relprop(self,R):
        iself = copy.deepcopy(self); iself.B *= 0
        nself = copy.deepcopy(self); nself.B *= 0; nself.W = numpy.minimum(0,nself.W)
        pself = copy.deepcopy(self); pself.B *= 0; pself.W = numpy.maximum(0,pself.W)
        X,L,H = self.X,self.X*0+utils.lowest,self.X*0+utils.highest

        Z = iself.forward(X)-pself.forward(L)-nself.forward(H)+1e-9; S = R/Z
        R = X*iself.gradprop(S)-L*pself.gradprop(S)-H*nself.gradprop(S)
        return R

class NextConvolutionAlphaBeta(modules.Convolution,object):

    def __init__(self,name,alpha):
        super(self.__class__, self).__init__(name)
        self.alpha = alpha
        self.beta  = alpha-1
        
    def relprop(self,R):
        pself = copy.deepcopy(self); pself.B *= 0; pself.W = numpy.maximum( 1e-9,pself.W)
        nself = copy.deepcopy(self); nself.B *= 0; nself.W = numpy.minimum(-1e-9,nself.W)

        X = self.X+1e-9
        ZA = pself.forward(X); SA =  self.alpha*R/ZA
        ZB = nself.forward(X); SB = -self.beta *R/ZB
        R = X*(pself.gradprop(SA)+nself.gradprop(SB))
        return R

```

I'm sure that i followed this tutorial and also implemented same in maxpooling.

what is the difference? please help me

**Comment by VigneshSrinivasan10** [comment]
Hi @segnam, 

For larger models, it is best to distribute the computation of lrp for different layers to a combination of cpu and gpu. Though, 3D models can be memory-consuming. 

Please update the latest version of the repository for best results and efficient computing. The difference in the results from the python version and the tensorflow version could be from the different stabilizer term added to the denominator. 

Best,

**Comment by sebastian-lapuschkin** [comment]
Can you specify what you mean by difference?
Are the resulting relevance maps qualitatively unrelated, or just numerically deviating to a small degree?
Keep in mind that between many frameworks, there will always be a small numerical difference in the computations, which already may be rooted in the process of copying model parameters:

If you have an array of numpy.float64, for example, and cast that array to 32 bit floating point numbers, the rounding process performed by numpy will yield different results than similar functions implemented by e.g. keras + a tensorflow backend. If you choose different hardware (gpu vs cpu), that is a whole different story.

About what kind and degree of difference are we talking here?

**Comment by sebastian-lapuschkin** [comment]
short answer:

the tutorial on heatmapping.org covers Deep Taylor Decomposition (DTD) from [this paper](https://www.sciencedirect.com/science/article/pii/S0031320316303582?via%3Dihub),

which is a bit more constricted in its assumptions, e.g. the inputs of a layer are always >= 0, the bias is negative, etc. Thus, the decompositions deviate slightly and do not neccesarily work with networks not fulfilling those additional assumptions.

DTD is a more specialized sibling of LRP, following the theory of Taylor approximation-based relevance decomposition for each and every neuron in a NN.

FYI: it is not very helpful if you completely edit your whole initial post if you have additional questions. Just add a new  message to the thread, so future readers can still follow it.

**Comment by wjNam** [comment]
Thank you for your answering.

It has helped a lot.
